var Tuner = ["FRS", "BRZ", "240", "WRX", "STi", "ACURATL"];
var Muscle = ["Chevelle", "NovaSS", "Charger", "Challenger"];
var Exotic = ["Pagani", "McClaren", "GTR", "Ferrari", "Lamborghini"];

for (var i = 0; i < Tuner.length; i++) {
    console.log(Tuner[i]);
}
console.log("===========extend============");

for (var M = 0; M < Muscle.length; M++) {
    console.log(Muscle[M]);
}
console.log("===========more============");
for (var E = 0; E < Exotic.length; E++) {
    console.log(Exotic[E]);
}